### PR TITLE
Added update method support for "cloudconnexa_connector" resource

### PR DESCRIPTION
**Pull request by michaelfmnk**

### CODE REVIEW

**Comment by michaelfmnk** [comment]
https://github.com/OpenVPN/terraform-provider-cloudconnexa/issues/12

**Review by patoarvizu — APPROVED** [review]
👍

**Comment by sahaqaa** [comment]
Manual tests were done:
```
+ Create resources
cloudconnexa_network
cloudconnexa_connector

+ Read (Plan) - no drift should be detected
+ Update
+ Destroy

+ Compare output of datasource connector vs Swagger
// there are some differences, created backlog ticket internally

+ Compare output of datasource network vs Swagger
// there are some differences, created backlog ticket internally

+ Import and run plan -> no drift should be detected
cloudconnexa_network (not working, created backlog ticket internally)
cloudconnexa_connector (all OK)
```

**Review by sahaqaa — APPROVED** [review]
:+1:

**Review by arslanbekov — APPROVED** [review]

**Pull request merged**
